name: Build Angular and update /docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build  # or ng build if globally installed

      - name: Copy browser build to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r dist/*/browser/* docs/

      # - name: Create .nojekyll for GitHub Pages
      #   run: touch docs/.nojekyll

      - name: Commit and push updated docs
        run: |
          git config --global ritshkr1 'github-actions[bot]'
          git config --global riteshkumar.dev2@gmail.com 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "🔧 Auto-update /docs from build"
          git push
        continue-on-error: true  # Avoid failing if no changes
